# meta file for fail2ban
---
galaxy_info:
  role_name: fail2ban
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up fail2ban in Debian-like systems
  license: MIT
  min_ansible_version: 2.6.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - system
    - networking
dependencies: []
